### PR TITLE
Add Logging documentation #23

### PR DESCRIPTION
**Pull request by xt1**
New ILogger system documented

### CODE REVIEW

**Review by SuperOfficeDevNet — COMMENTED** [review]
Our markdown file name conventions are:
1. No spaces. Instead of spaces use a dash '-'. 
2. No periods '.' in the file name for textual content (except yml API reference files). 
3. Lowercase. All filenames are lowercase (except yml API reference files).

UIDs should be descriptive and unique. Are often same as "area-topic-subject"

**Comment by digitaldiina** [comment]
- What is the relationship between the files, in which order should they be read/listed?
- All files should have a # H1 heading in addition to the title metadata field. The H1 is used for display on the page, the title field is used for TOC generation and SEO.
- The so.date metadata field follows the MM.DD.YYYY format.
- Folder and file names should be *italic* and not `code`.
- Sentences should be complete and not split by code, a list, a table, or similar.
- In fenced code blocks: start line 1 at the margin (no indent); use preferably 2, or alternatively, 4 spaces for indentation; don't escape special characters.

**Review by digitaldiina — COMMENTED** [review]
Edited file based on my previous comment.

**Review by SuperOfficeDevNet — APPROVED** [review]
OK, good. Thanks!

**Pull request merged**
